- name: Ensures /etc/systemd/system/origin-master-api.service.d dir exists
  file: path=/etc/systemd/system/origin-master-api.service.d state=directory

- name: Increase master start timeout
  template: src=origin-master-api.service.d/origin-master-api.service dest=/etc/systemd/system/origin-master-api.service.d/origin-master-api.service

- name: check INPUT vrrp firewall rules
  shell: iptables -C INPUT -i eth0 -d 224.0.0.0/8 -p vrrp -j ACCEPT
  register: check_vrrp_input
  failed_when: "check_vrrp_input.rc != 0 and 'Bad rule' not in check_vrrp_input.stderr"
  changed_when: False

- name: add INPUT vrrp firewall rules
  shell: iptables -I INPUT -i eth0 -d 224.0.0.0/8 -p vrrp -j ACCEPT
  when: check_vrrp_input.rc == 1

- name: check OUPUT vrrp firewall rules
  shell: iptables -C OUTPUT -o eth0 -d 224.0.0.0/8 -p vrrp -j ACCEPT
  register: check_vrrp_output
  failed_when: "check_vrrp_output.rc != 0 and 'Bad rule' not in check_vrrp_output.stderr"
  changed_when: False

- name: add OUPUT vrrp firewall rules
  shell: iptables -I OUTPUT -o eth0 -d 224.0.0.0/8 -p vrrp -j ACCEPT
  when: check_vrrp_output.rc == 1

# Configure prerouting
- name: check prerouting firewall rules
  shell: iptables -t nat -C PREROUTING -d 192.168.124.10/32 -i eth0 -p tcp -m tcp --dport 8443 -j DNAT --to-destination {{ vrrp_legacy_ip }}:8443
  register: check_prerouting
  failed_when: "check_prerouting.rc != 0 and 'No chain/target/match by that name' not in check_prerouting.stderr"
  changed_when: False

- name: add prerouting firewall rules
  shell: iptables -t nat -I PREROUTING -d 192.168.124.10/32 -i eth0 -p tcp -m tcp --dport 8443 -j DNAT --to-destination {{ vrrp_legacy_ip }}:8443
  when: check_prerouting.rc == 1

# Configure postrouting
- name: check prerouting firewall rules
  shell: iptables -t nat -C POSTROUTING -o eth0 -p tcp -m tcp --sport 8443 -j MASQUERADE
  register: check_postrouting
  failed_when: "check_postrouting.rc != 0 and 'No chain/target/match by that name' not in check_postrouting.stderr"
  changed_when: False

- name: add INPUT vrrp firewall rules
  shell: iptables -t nat -A POSTROUTING -o eth0 -p tcp -m tcp --sport 8443 -j MASQUERADE
  when: check_postrouting.rc == 1

- name: save firewall rule
  shell: iptables-save > /etc/sysconfig/iptables

- name: install the latest version of Keepalived
  yum: name=keepalived state=latest

- name: copy Openshift Master health check script
  template : src=keepalived/check_openshift_master.sh dest=/etc/keepalived/check_openshift_master.sh owner=root group=root mode=0755

- name: copy Keepalived configuration
  template : src=keepalived/keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf owner=root group=root mode=0644
  register: keepalived_conf

- name: restart Keepalived
  service: name=keepalived state=restarted enabled=yes
  when: keepalived_conf.changed 
